### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by olafmarcos** [panzi/verify-ehc#13]
I get this error:

Traceback (most recent call last):
  File "verify_ehc.py", line 30, in <module>
    from jose import jwt, jws, jwk # type: ignore
  File "/home/olaf/.local/lib/python3.7/site-packages/jose.py", line 546
    print decrypt(deserialize_compact(jwt), {'k':key},
                ^

I'm passing the ehc_code as 'HC1:NCFOXN%TSMAHN-HUN8.....' string. Is it correct?

**Comment by panzi** [comment]
You have the wrong jose library installed. The library called `jose` is broken (uses Python 2 syntax), you need to remove it and install `python-jose` instead. In particular install it parametrized as `python-jose[cryptography]`, see `requirements.txt`.

**Comment by olafmarcos** [comment]
Thank you very much.

Sorry, not seen the version requirement....

Working like a charm!
