### ISSUE TITLE
refactoring to use it as a module / package?

### ISSUE THREAD

**Issue by wolfgang-reutz** [panzi/verify-ehc#14]
Hi,

as I need to use health certificate verification in a Django web app I would propose to refactor the code to be used as a package.

I plan to do:
- outsource to code to a package and import the methods / classes in the main application file (verify_ehc.py)
- replace the print() statements to return values and print the text in a single place (main() of verify_ehc.py) to play nice with Webapps as these are normally run in a thread by apache / nginx
- maybe add python logging to allow verbose logging and info / warning / errors
- the result should be a standalone application that outputs all the data to the command line **but** also allow to be used as a drop-in module for e.g. webapps or other python applications with logging

What do you think about that idea?
If I refactor it, would it be possible to be merged (pull request)?

**Comment by panzi** [comment]
Yeah sorry but that is not the scope of this script. As you can see this script has a lot of `print()`s and stuff in it that wouldn't be needed at all in another context. If you reduce it to the core functionality of decoding and verifying of the QR-code it will be a fraction of the size. See e.g. (provided by the EU): https://github.com/ehn-dcc-development/ehn-sign-verify-python-trivial/blob/main/hc1_verify.py (Ignore the weird name mangling in lines 272 to 276.)

So you can extract whatever functionality you need from my script (under the terms of the MIT license) and make your own lib. :D
