### ISSUE TITLE
CERTS_URL_AT_GREENCHECK = 'https://greencheck.gv.at/api/v2/masterdata'

### ISSUE THREAD

**Issue by tech-2** [panzi/verify-ehc#15]
CERTS_URL_AT_GREENCHECK = 'https://greencheck.gv.at/api/v2/masterdata'

{
  "message" : "Die Version dieser Anwendung ist veraltet! Bitte installieren Sie die aktuellste Version!",
  "detailedMessage" : "Die Version dieser Anwendung ist veraltet! Bitte installieren Sie die aktuellste Version!"
}

**Comment by panzi** [comment]
Can't reproduce. Are you using the current version of the script?

**Comment by panzi** [comment]
Even though I don't get that error I've bumped the `x-app-version` header to be the same as the web app uses. Does it still happen for you?

**Comment by tech-2** [comment]
If you open it in the webbrowser it isn't any more up to date.

**Comment by panzi** [comment]
You get this message in the web browser because you don't send the `x-app-version: 1.3` header that way. Look at all the headers that I set in the source! https://github.com/panzi/verify-ehc/blob/main/verify_ehc.py#L576-L586

You can access the trust list using curl like this:
```bash
curl -H 'x-app-version: 1.3' -H 'x-app-type: browser' -H 'Accept: application/json' https://greencheck.gv.at/api/v2/masterdata
```
