### ISSUE TITLE
https://greencheck.gv.at/api/v2/masterdata throw error

### ISSUE THREAD

**Issue by senzacionale** [panzi/verify-ehc#17]
curl -H 'x-app-version: 1.3' -H 'x-app-type: browser' -H 'Accept: application/json' https://greencheck.gv.at/api/v2/masterdata

return an error

{
  "message" : "Die Version dieser Anwendung ist veraltet! Bitte aktualisieren Sie die Anwendung durch neues Laden der Seite!",
  "detailedMessage" : "Die Version dieser Anwendung ist veraltet! Bitte aktualisieren Sie die Anwendung durch neues Laden der Seite!"
}

Is there any new version?

**Comment by panzi** [comment]
Well, yeah. `verify_ehc.py` sends `x-app-version: 1.4`, just like the greencheck web-app does when you look at it in your browser's developer tools. But that's not an endpoint that should be used by anyone other than the greencheck app anyway. I probably should remove it from the script.
