### ISSUE TITLE
Any changes with the 3rd vaccination?

### ISSUE THREAD

**Issue by Peonlicious** [panzi/verify-ehc#25]
Hello,

Did something change with the implementation of the 3rd vaccination? Whenever i try to read a person's 3rd vac-qr-code, the script throws errors.

looking like this:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\verify-ehc-main\verify_ehc.py", line 2456, in <module>
    main()
  File "C:\Users\User\Desktop\verify-ehc-main\verify_ehc.py", line 2425, in main
    ehc_msg = decode_ehc(ehc_code)
  File "C:\Users\User\Desktop\verify-ehc-main\verify_ehc.py", line 1651, in decode_ehc
    data = zlib.decompress(data)
zlib.error: Error -3 while decompressing data: invalid literal/length code

Teststing 1st and 2nd vacc there are no problems. I was under the impression that everything stays the same, no matter the vaccination numbers, only the payload would change accordingly

**Comment by panzi** [comment]
That is weird and interesting. I haven't tested any 3rd vaccination record myself yet. (I don't have my 3rd vaccination yet.) But it's weird that it fails at the zlib decompression stage! That is several decoding steps before you get to information about the vaccination.What country do your certificates come from? I guess you can't share an example?

**Comment by Peonlicious** [comment]
It is from Germany, i sent it to the email which you have on your profile

It is from a family member so i would rather not post it public. If needed i am sure can sent the qr itself

**Comment by trasgu82** [comment]
I also have some family members with 3rd vaccination and the script works as with the 1st and the 2nd ones, no problem at all.
It may be a problem of some specific QR codes. Weeks ago I also found a PCR QR code that also gave errors during decoding, but I could not keep it to debug.

**Comment by panzi** [comment]
I wonder if it could just be a bad scan? I mean, QR-codes do error correction, but who knows? In that example it really looks like the deflate stream is broken. The infgen tool says `infgen warning: invalid deflate data -- invalid code`.

**Comment by Peonlicious** [comment]
Thats weird, i get the same problem with 2 different scanners. I will try and read the qr later with my phone and check if i get a different ciphertext

**Comment by Peonlicious** [comment]
ok it seems to be the hardware, but io wonder what it does. i just scanned the qr with my phone and pasted the cipher into the tool, it is working

**Comment by panzi** [comment]
Great to hear you managed to scan it correctly now! Dumb that the scanner is not working right. ☹️
