### ISSUE TITLE
[Errno 22] Invalid argument

### ISSUE THREAD

**Issue by trasgu82** [panzi/verify-ehc#27]
`verify_ehc.py --certs-from CH--save-certs test.cbor --allow-pubkey-only`
OR
`verify_ehc.py --certs-from GB --save-certs test.cbor --allow-pubkey-only`
OR
`verify_ehc.py --certs-from NO --save-certs test.cbor --allow-pubkey-only`

RESULT
```
Traceback (most recent call last):
  File "D:\[...]\verify_ehc.py", line 2491, in <module>
    main()
  File "D:\[...]\verify_ehc.py", line 2429, in main
    save_certs(certs, certs_path, args.allow_public_key_only)
  File "D:\[...]\verify_ehc.py", line 1955, in save_certs
    entry['na'] = int(not_valid_after.timestamp())
OSError: [Errno 22] Invalid argument
```

**Comment by panzi** [comment]
Weird. I can't reproduce that and also that trace looks weird. The shown line isn't line 1955 in the source (do you have the latest version?) and in any case it should never cause an OSError. I can imagine a ValueError, OverflowError, TypeError, or AttributeError. But to my understanding of the `timestamp()` method there can't be an OSError? Weird.

Verify that you are using the latest version, and if the problem persists please add `print(not_valid_after)` before the offending line (at the same indentation level) and show me the output right before the crash. Thank you!

**Comment by trasgu82** [comment]
Sorry, I forgot I've added some comments so line numbers doesn't match.
I've just downloaded again last version, the one you commited one hour ago.

Using original script...
`verify_ehc.py --certs-from GB --save-certs test.cbor --allow-pubkey-only`

OUTPUT
```
Traceback (most recent call last):
  File "D:\[...]\verify_ehc.py", line 2485, in <module>
    main()
  File "D:\[...]\verify_ehc.py", line 2423, in main
    save_certs(certs, certs_path, args.allow_public_key_only)
  File "D:\[...]\verify_ehc.py", line 1949, in save_certs
    entry['na'] = int(not_valid_after.timestamp())
OSError: [Errno 22] Invalid argument
```

I add `print(not_valid_after) ` in line 1948...

OUTPUT
```
1970-01-01 00:00:00
Traceback (most recent call last):
  File "D:\[...]\verify_ehc.py", line 2486, in <module>
    main()
  File "D:\[...]\verify_ehc.py", line 2424, in main
    save_certs(certs, certs_path, args.allow_public_key_only)
  File "D:\[...]\verify_ehc.py", line 1950, in save_certs
    entry['na'] = int(not_valid_after.timestamp())
OSError: [Errno 22] Invalid argument
```

**Comment by panzi** [comment]
This is strange. I cannot reproduce this problem here. I wonder if it's Windows specific (I'm on Linux and have no access to a Windows machine). If you do these things on the Python shell, what do you get?

```Python
>>> from datetime import *
>>> datetime(1970,1,1).timestamp()
-3600.0
>>> datetime(1970,1,1,tzinfo=timezone.utc).timestamp()
0.0
```

**Comment by trasgu82** [comment]
On a Windows machine I get (with Python 3.9.6)
```
>>> from datetime import *
>>> datetime(1970,1,1).timestamp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
>>> datetime(1970,1,1,tzinfo=timezone.utc).timestamp()
0.0
```

On a raspberry I get (with Python 3.9.1 )
```
>>> from datetime import *
>>> datetime(1970,1,1).timestamp()
-3600.0
>>> datetime(1970,1,1,tzinfo=timezone.utc).timestamp()
0.0
```

On the raspberry `verify_ehc.py --certs-from GB --save-certs test.cbor --allow-pubkey-only` executes with no errors, so it's likely a Windows problem (as I've tried in 3 different machines with same result)

**Comment by panzi** [comment]
Ok, I've pushed something that should fix that. Its all a timezone confusion and the code before the fix might have produced wrong timestamps anyway if the users time zone is not UTC.

**Comment by trasgu82** [comment]
Downloaded and tested! It now executes with no errors in Windows... Thanks!!!
