### ISSUE TITLE
[Feature] Check if certificates are revoked through a CRL

### ISSUE THREAD

**Issue by Cqoicebordel** [panzi/verify-ehc#5]
This one is a big one, and I don't know if it's already in your TODO list.

For an ehc to be valid, the signature must be checked against the certificate, the dates should match, and the certificate shouldn't be revoked.  
Right now, you do the first two. Doing the third would help completness.

Of course, there are several big hurdles, notably that I don't know if any CRL are released right now, and that CRLs could differ country from country.

In any case, it's not a necessary feature. I'm not expecting it, I just thought it would be useful to put it on your radar. Don't hesitate to close if you don't want to do it :)

**Comment by panzi** [comment]
Sadly I don't know about any revocation lists. The trust lists that I've got where in part found by reverse engineering (see: https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10). I haven't found any public revocation lists. I would assume that the trust lists already have revoked public keys stripped, so as long as that is up to date it should be fine. European Health Certificates themselves aren't revoked (I was told in the thread linked above).

**Comment by panzi** [comment]
If you can find out more about this, please do tell!

**Comment by Cqoicebordel** [comment]
Having it removed from the list could work, but could be troublesome too, as every country in EU should update fairly regularly to be sure to not have the revoked certificate.

https://ec.europa.eu/health/sites/default/files/ehealth/docs/trust-framework_interoperability_certificates_en.pdf mention it, but just in passing.

I have followed from a distance the thread you are mentioning (at least, its start), and one link in it prompted me to file this FR : I've dumbly b64decoded https://greencheck.gv.at/api/masterdata, and saw several links in it, notably some `.crl` (like http://crl.eadtrust.eu/eadtrust-subca-ecc256eadlp2019.crl or http://repository.incert.lu/csca.crl). I have no idea if they are relevant to us, and in fact, they are probably not.  
But "probably" isn't 100%, hence my mentioning it :)

In any case, I'll keep an eye open if I find good docs about that !

**Comment by panzi** [comment]
Hm, yes indeed, there are URLs in there. Have to take a look at that. That crypto stuff is all new to me.
